# global time
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # database
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false&useUnicode=true&characterEncoding=utf-8&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: my-secret-pw
    driver-class-name: com.mysql.cj.jdbc.Driver
  # qq邮箱
  mail:
    host: smtp.qq.com
    username: 780357902@qq.com
    password: euoocjbkzfqdbdcf
    properties:
      mail:
        stmp:
          auth: true
          starttls:
            enable: true
            required: true
  # redis
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    timeout: 2000
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1
  # session
  session:
    # session存储类型为 redis 空时禁用
    store-type: redis
    redis:
      # 更新策略，ON_SAVE在调用#SessionRepository#save(Session)时，在response commit前刷新缓存，
      # IMMEDIATE只要有任何更新就会刷新缓存,默认为on_save
      flush-mode: on_save
      # 存储session的密钥的命名空间 默认spring:session
      namespace: spring:session

# mybatis
mybatis:
  config-location: classpath:db/mybatis/mybatis_config.xml
