# base config
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # 激活配置
  profiles:
    active: dev
  # qq邮箱
  mail:
    host: smtp.qq.com
    username: 780357902@qq.com
    password: euoocjbkzfqdbdcf
    properties:
      mail:
        stmp:
          auth: true
          starttls:
            enable: true
            required: true

# 配置slq打印日志
mybatis-plus:
  # 自定义xml文件路径
  mapper-locations: classpath:/db/mapper/*Mapper.xml
  # 自定义xml文件中用到的实体类路径
  type-aliases-package: hello.entity
  configuration:
    # 开启驼峰映射
    map-underscore-to-camel-case: true
    cache-enabled: false
    # 返回map时，true:当查询数据为空时字段返回为null；false:不加这个查询数据为空时，字段将被隐藏
    call-setters-on-nulls: true
    # sql日志打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    jdbc-type-for-null: 'null'
